### PR TITLE
feat: add bidirectional streaming rpc of functions query

### PR DESCRIPTION
**Pull request by Ink-33**
Add method FunctionsQueryStream to servive server.Runner. This api works like FunctionsQuery but is implemented in bidirectional streaming.

### CODE REVIEW

**Comment by Ink-33** [comment]
`atomic.Uint64` was added in go 1.19 but ci is using 1.18.x.  Should we update the go version or use `sync.Mutex` to replace it?

**Comment by LinuxSuRen** [comment]
> `atomic.Uint64` was added in go 1.19 but ci is using 1.18.x. Should we update the go version or use `sync.Mutex` to replace it?

Are there any simple alternative solution to replace `atomic.Uint64`? Or, we could upgrade the Go version if you have other solid reason.

**Comment by Ink-33** [comment]
> > `atomic.Uint64` was added in go 1.19 but ci is using 1.18.x. Should we update the go version or use `sync.Mutex` to replace it?
> 
> Are there any simple alternative solution to replace `atomic.Uint64`? Or, we could upgrade the Go version if you have other solid reason.

Yes, `atomic.AddUint32` can do the same work as I think uint32 is enough to handle this situation.

**Comment by LinuxSuRen** [comment]
OK. Then we can use `atomic.AddUint32` for now until we have other reason to replace it.

**Review by LinuxSuRen — APPROVED** [review]
LGTM

**Comment by LinuxSuRen** [comment]
Welcome @Ink-33 to be the 8th contriutor of API-Testing.

**Pull request merged**
