### PR TITLE
feat: support to set the prefix of mock server

### PR DESCRIPTION
**Pull request by LinuxSuRen**
**What type of PR is this?**

**What this PR does / why we need it**:
Allowing user to set the prefix can meet more use cases.

**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Comment by LinuxSuRen** [comment]
hi @YukiCoco, please feel free to help to review this PR. Thanks.

**Comment by YukiCoco** [comment]
> hi @YukiCoco, please feel free to help to review this PR. Thanks.

I just saw the update that the PR has been successfully merged and closed—thanks for taking care of it! I must apologize for missing your initial message in my crowded email inbox. I'm truly sorry for not being able to provide my input on time. I’d be grateful for any opportunity to contribute to future projects. Please don't hesitate to reach out.

**Comment by LinuxSuRen** [comment]
No worry. Please let me know if you find any things that need to be improved in this PR.

By the way, there are many things we can do on [the mock server part](https://github.com/LinuxSuRen/api-testing/tree/master/pkg/mock). For example:

* Random delay response support
* Built-in auth support
* Multiple levels API paths support.
  * Currently, it can serve like `/v1/projects`, but it not support `/v1/projects/{demo}/users/{someone}`
* Control the mock server on the web page

**Comment by YukiCoco** [comment]
> No worry. Please let me know if you find any things that need to be improved in this PR.
> 
> By the way, there are many things we can do on [the mock server part](https://github.com/LinuxSuRen/api-testing/tree/master/pkg/mock). For example:
> 
> * Random delay response support
> * Built-in auth support
> * Multiple levels API paths support.
>   
>   * Currently, it can serve like `/v1/projects`, but it not support `/v1/projects/{demo}/users/{someone}`
> * Control the mock server on the web page

I have tested this code and it works well. I will try to support more mock functions.

**Pull request merged**
