### PR TITLE
[FIXED] grammatical errors in README.md

### PR DESCRIPTION
**Pull request by kuv2707**

### CODE REVIEW

**Review by LinuxSuRen — APPROVED** [review]
This is much better. Thanks for your effort.

**Comment by LinuxSuRen** [comment]
hi @kuv2707 , there are some `good-first-issue` below. Please feel free to pick up some if you are interested.

https://github.com/LinuxSuRen/api-testing/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22

**Comment by kuv2707** [comment]
Hi @LinuxSuRen 
I have started working on some of the issues.
Meanwhile, it would be great if you added the hacktoberfest-added label to this PR.

**Comment by LinuxSuRen** [comment]
> Meanwhile, it would be great if you added the hacktoberfest-accepted label to this PR.

Sure. Happy to work with you.

**Pull request merged**
