### PR TITLE
feat: add github action to check md link

### PR DESCRIPTION
**Pull request by yuluo-yx**
- For #257

### CODE REVIEW

**Comment by LinuxSuRen** [comment]
Below are the correct badge link.

[Codacy Badge](https://app.codacy.com/gh/LinuxSuRen/api-testing/dashboard?utm_source=gh&utm_medium=referral&utm_content=&utm_campaign=Badge_grade)

[Codacy Badge](https://app.codacy.com/gh/LinuxSuRen/api-testing/dashboard?utm_source=gh&utm_medium=referral&utm_content=&utm_campaign=Badge_coverage)

**Comment by yuluo-yx** [comment]
> 以下是正确的徽章链接。
> 
> [科达西徽章](https://app.codacy.com/gh/LinuxSuRen/api-testing/dashboard?utm_source=gh&utm_medium=referral&utm_content=&utm_campaign=Badge_grade)
> 
> [科达西徽章](https://app.codacy.com/gh/LinuxSuRen/api-testing/dashboard?utm_source=gh&utm_medium=referral&utm_content=&utm_campaign=Badge_coverage)

got it.

**Comment by yuluo-yx** [comment]
> Below are the correct badge link.
> 
> [Codacy Badge](https://app.codacy.com/gh/LinuxSuRen/api-testing/dashboard?utm_source=gh&utm_medium=referral&utm_content=&utm_campaign=Badge_grade)
> 
> [Codacy Badge](https://app.codacy.com/gh/LinuxSuRen/api-testing/dashboard?utm_source=gh&utm_medium=referral&utm_content=&utm_campaign=Badge_coverage)

got it.

**Comment by yuluo-yx** [comment]
@LinuxSuRen  About "Build / APITest (pull_request)", may refer to this issue: https://github.com/thollander/actions-comment-pull-request/issues/30

**Review by LinuxSuRen — APPROVED** [review]
Good job!

**Comment by LinuxSuRen** [comment]
> @LinuxSuRen About "Build / APITest (pull_request)", may refer to this issue: [thollander/actions-comment-pull-request#30](https://github.com/thollander/actions-comment-pull-request/issues/30)

It seems to be caused by no permission to get the corresponding secret from GitHub

**Comment by yuluo-yx** [comment]
> > @LinuxSuRen About "Build / APITest (pull_request)", may refer to this issue: [thollander/actions-comment-pull-request#30](https://github.com/thollander/actions-comment-pull-request/issues/30)
> 
> It seems to be caused by no permission to get the corresponding secret from GitHub

yep. 🥲

**Pull request merged**
