### PR TITLE
Support to generator Python code from a HTTP testCase #365

### PR DESCRIPTION
**Pull request by zhouzhou1017**
add license and fix file

### CODE REVIEW

**Review by LinuxSuRen — CHANGES_REQUESTED** [review]
image
image

Please make sure you have a correct git config. See also:

```shell
git config --global user.email=xxx
git config --global user.name=xxx
```

**Comment by LinuxSuRen** [comment]
This is replacement of https://github.com/LinuxSuRen/api-testing/pull/371

**Comment by LinuxSuRen** [comment]
image

实际上，所有的 commits 都需要符合的，目前系统会认为这个 PR 包含了两个人的 commit 记录。

**Review by LinuxSuRen — APPROVED** [review]
Everything is ok now. Thanks for your patience especially since I gave you many comments.

And welcome to be the 17th contributor. Hopefully, you can learn something from this.

**Comment by zhouzhou1017** [comment]
Thanks a lot for your precious comments and advice. It`s my first time for pr. I do learn a lot from it. Thanks again.

**Comment by LinuxSuRen** [comment]
So happy to hear that.

**Pull request merged**
