### PR TITLE
chore: add issue comment github actions

### PR DESCRIPTION
**Pull request by yuluo-yx**
- For #373

### CODE REVIEW

**Review by LinuxSuRen — COMMENTED** [review]
It looks like very useful. But would you mind giving us a few examples of those projects which are using it?

**Comment by yuluo-yx** [comment]
> It looks like very useful. But would you mind giving us a few examples of those projects which are using it?

Sure.
1. https://github.com/envoyproxy/gateway/blob/main/.github/workflows/issue-comment.yaml
2. https://github.com/kubernetes/kubernetes/issues/124407#issuecomment-2066737103

istio & k8s etc...

**Comment by yuluo-yx** [comment]
@LinuxSuRen https://github.com/yuluo-yx/deigmata-paideias/issues/2

**Review by LinuxSuRen — APPROVED** [review]
LGTM

**Pull request merged**
