### PR TITLE
feat: Support to generator JavaScript code from a HTTP testCase.

### LINKED ISSUE #395: Support to generator JavaScript code from a HTTP testCase
Below is the Golang code generator.

https://github.com/LinuxSuRen/api-testing/blob/e05ff4b485e0c525ea7f78b4d653ddc230c5716e/pkg/generator/golang_generator.go
Similarly, we could add the Java code generator. Please feel free to do some research to find out how to make an HTTP request in JavaScript.

See others https://github.com/LinuxSuRen/api-testing/issues/112

### PR DESCRIPTION
**Pull request by YukiCoco**
add javascript generator.
add javascript code generator test data.

**What type of PR is this?**
feat: Support to generator JavaScript code from a HTTP testCase.
**Which issue(s) this PR fixes**:
Fixes #395

### CODE REVIEW

**Review by LinuxSuRen — COMMENTED** [review]
I found an error when try it in the Chrome console.

image

**Comment by YukiCoco** [comment]
> I found an error when try it in the Chrome console.
> 
> image

In browsers or Node.js, sending an HTTP GET request with a body is not allowed, and it will be blocked by the browser. However, I've still generated code for this situation. When using a GET request in this manner, I've added a comment: `// WARNING: JavaScript does not allow a body to be sent with GET requests.` This is to prompt the user to switch to a different request method.

Reference: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/GET

**Comment by LinuxSuRen** [comment]
> I've added a comment: `// WARNING: JavaScript does not allow a body to be sent with GET requests.` This is to prompt the user to switch to a different request method.

This is ok to me. How about adding comment in line 24 and 25? So, those source code can work well. Even we can add a console output, for example:

```
console.log('the body is ignored because this is a GET request')
```

**Comment by YukiCoco** [comment]
This looks better! I will implement it later.

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by YukiCoco** [comment]
Now, the new code generator looks like this:
```javascript
async function makeRequest() {
    const headers = new Headers();
    headers.append("User-Agent", "atest");
    const cookieHeader = [
        "name=value",
    ].join("; ");
    headers.append("Cookie", cookieHeader);

    const requestOptions = {
        method: "GET",
        headers: headers,
        redirect: "follow"
    };
    console.log('the body is ignored because this is a GET request')
    /*
    let body = `{"key": "value"}`;
    requestOptions.body = body;
    */

    try {
        const response = await fetch("https://www.baidu.com", requestOptions);
        if (response.ok) { // Check if HTTP status code is 200/OK
            const text = await response.text();
            console.log(text);
        } else {
            throw new Error('Network response was not ok. Status code: ' + response.status);
        }
    } catch (error) {
        console.error('Fetch error:', error);
    }
}

makeRequest();
```

**Review by LinuxSuRen — APPROVED** [review]
I have tested it manually. It works well. Thanks for your effort. And SO HAPPY to have as the 18th contributor.

This project will be better because of you.

image

**Pull request merged**
