### PR TITLE
feat: refactor atest ui

### PR DESCRIPTION
**Pull request by yuluo-yx**
- For #416

### CODE REVIEW

**Comment by LinuxSuRen** [comment]
hi @yuluo-yx I try to fix the conflicts, see also https://github.com/yuluo-yx/api-testing/pull/4

**Review by LinuxSuRen — COMMENTED** [review]
I start it via `make run-server`. I found some issues, see also

image
image

**Comment by yuluo-yx** [comment]
it seems  that: `▲ [WARNING] CSS nesting syntax is not supported in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14") [unsupported-css-nesting]` I try solve it,

**Review by SamYSF — APPROVED** [review]

**Comment by LinuxSuRen** [comment]
Let's close this PR for now until you have time to continue.

**Pull request closed without merging**
